### ISSUE TITLE
Generating attributes with special caracters

### ISSUE THREAD

**Issue by pedrohma** [bladefist/JsonUtils#25]
Hello guys!

I've inserted this JSON to the application: 

`{"?xml":{"@version":"1.0","@encoding":"UTF-8","@standalone":"yes"},"ns2:FeedAcknowledgement":{"@xmlns:ns2":"http://walmart.com/","ns2:feedId":"xxxxxx"}}`

And I got this as result:

![image](https://user-images.githubusercontent.com/6583751/36570382-9d8c70dc-17e6-11e8-9a09-91f9c21b1233.png)

As you can see it generated the attributes with special caracters... There is a way we can remove all this special caracters and return clean attributes?

Thanks!

**Comment by Crossbow78** [comment]
Often running into this myself.

This seems somewhat related to issue #28, where the generator does not generate valid property names. I'd suggest a simple approach where the member name is sanitized in the `FieldInfo` constructor, so it will automatically apply to _any_ language generator.

Sanitation process could be as follows:
* Any sequence of symbols is replaced by a single underscore
* A leading digit is prefixed by an underscore

Examples:
* `@xmlns:ns2` becomes `_xmlns_ns2`
* `@&test-*-value` becomes `_test_value`
* `70pct` becomes `_70pct`
