### ISSUE TITLE
jsonutils.com is down

### ISSUE THREAD

**Issue by fooooooooooooooo** [bladefist/JsonUtils#49]
has been for a few days

**Comment by dvdnhm** [comment]
I guess it is not coming back

**Comment by bladefist** [comment]
Apologies, the server that was hosting this got fried.  I don't have the time at the moment to deal with new hosting and there are probably better alternatives out there at this point.  It's open source though so if anyone wants to host it contact me, could potentially point dns to it.

**Comment by dvdnhm** [comment]
I can spare a server for it.

**Comment by bladefist** [comment]
Sites back up now.  Hosted by someone in the community.
