### ISSUE TITLE
Support for Typescript interface generation

### ISSUE THREAD

**Issue by GFoley83** [bladefist/JsonUtils#8]
Just wondering if you plan on supporting Typescript interface generation at some point in the future.

**Comment by bladefist** [comment]
@GFoley83 If you or someone else wants to do a pull request,  would love to add it.  But myself, I do not have plans to add it.   We have javascript, so it may not be too hard to copy paste that template and modify it.  Thanks!

**Comment by bladefist** [comment]
@GFoley83 this was merged in today and released.
