### ISSUE TITLE
Feature request: Can you add a simple copy button?

### ISSUE THREAD

**Issue by Alexisvt** [bladefist/JsonUtils#9]
Hi nice project! I want to ask if you can add a simple copy button to the top JSON Utilities header like this:

![image](https://cloud.githubusercontent.com/assets/7120647/15512394/e8916278-219c-11e6-9cd2-efa8cbb2a384.png)

**Comment by bladefist** [comment]
I'll put it on my list.  I also happily accept pull requests if you have a moment to knock it out.

**Comment by bladefist** [comment]
this was added and released some time ago.
